# Generated by Django 3.1.2 on 2021-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='panner',
            field=models.ImageField(default=1, upload_to='movies/panner'),
            preserve_default=False,
        ),
    ]
