# Generated by Django 3.1.2 on 2021-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_panner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.cast'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='picture',
            field=models.ImageField(upload_to='movies/profile_picture'),
        ),
    ]
