# Generated by Django 3.1.2 on 2021-11-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='IdNumber',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='movies.idnumber'),
            preserve_default=False,
        ),
    ]
