# Generated by Django 3.1.2 on 2021-11-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_cast_idnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='IdNumber',
            new_name='idnumber',
        ),
    ]
